name: Flex
markdown: redcarpet
highlighter: pygments

baseurl: ""
permalink: /:title/

# Plugins
gems: 
  - jekyll-multiple-languages-plugin


# jekyll-multiple-languages-plugin settings:
languages: ["it", "en", "es"]

exclude_from_localizations: ["javascript", "images", "css", "Gemfile", "scripts", "favicon.ico", "LICENSE", "README.md"]
